### ISSUE TITLE
Include log examples in BasicFormatter docs?

### ISSUE THREAD

**Issue by ktoso** [Adorkable/swift-log-format-and-pipe#4]
From skimming documentation it is hard to decide which formatter to choose; 

Could docs of `.adorkable` https://adorkable.github.io/swift-log-format-and-pipe/Structs/BasicFormatter.html#/s:20LoggingFormatAndPipe14BasicFormatterV9adorkableACvpZ

in addition to:

> Adorkable’s go-to log format 😘

also include a small sample?

(same about the `.apple` one?)

**Comment by yoiang** [comment]
Hey @ktoso , great call!

That and the README should include examples of all the components in the `BasicFormatter` vs sorting through the API docs.

**Comment by yoiang** [comment]
@ktoso let me know if #5 is what you were thinking!

**Comment by yoiang** [comment]
Closing for now

**Comment by ktoso** [comment]
Thanks a lot for the follow up!
Submitted a post-merge review, hope this helps 👍 

https://github.com/Adorkable/swift-log-format-and-pipe/pull/5#pullrequestreview-286282310
